# api_config.yaml
# FastAPI application configurations

server:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 2

app:
  title: "Intelligent SQL Error Classifier API"
  description: "FastAPI server for multi-class SQL error classification using transformer models."
  version: "1.0.0"
  model_weights_path: "experiments/exp_claudios_codebert-base_42/checkpoints/checkpoint_best.pt"
  device: "cuda"                       # cuda, cpu, mps
  enable_cors: true
  allowed_origins:
    - "*"
